FROM centos:centos7

# Deletes a number of unit files which might cause issues
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

# Set up YUM Repositories
RUN yum -y install pygpgme yum-utils wget epel-release httpd; yum clean all; systemctl enable httpd.service
RUN yum -y update

# Configure Tyk Gateway
RUN touch /etc/yum.repos.d/tyk_tyk-gateway.repo
RUN echo -e "[tyk_tyk-gateway]\nname=tyk_tyk-gateway\nbaseurl=https://packagecloud.io/tyk/tyk-gateway/el/7/\$basearch\nrepo_gpgcheck=1\ngpgcheck=1\nenabled=1\ngpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020  https://packagecloud.io/tyk/tyk-gateway/gpgkey\nsslverify=1\nsslcacert=/etc/pki/tls/certs/ca-bundle.crt\nmetadata_expire=300" > /etc/yum.repos.d/tyk_tyk-gateway.repo

# Update your local cache
RUN yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-gateway' --enablerepo=epel

# Install Packages
RUN yum install -y tyk-gateway
#RUN /opt/tyk-gateway/install/setup.sh --dashboard=1 --listenport=8080 --redishost=127.0.0.1 --redisport=6379
RUN systemctl enable tyk-gateway

COPY ./copyfiles/entrypoint.sh /opt/tyk-gateway/entrypoint.sh

VOLUME ["/opt/tyk-gateway/"]

WORKDIR /opt/tyk-gateway/

CMD ["/usr/sbin/init"]

ENTRYPOINT ["./entrypoint.sh"]