FROM centos:centos7

# Deletes a number of unit files which might cause issues
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

# Set up YUM Repositories
RUN yum -y install pygpgme yum-utils wget epel-release httpd; yum clean all; systemctl enable httpd.service
RUN yum -y update

# Configure Tyk Dashboard
RUN touch /etc/yum.repos.d/tyk_tyk-dashboard.repo
RUN echo -e "[tyk_tyk-dashboard]\nname=tyk_tyk-dashboard\nbaseurl=https://packagecloud.io/tyk/tyk-dashboard/el/7/\$basearch\nrepo_gpgcheck=1\ngpgcheck=1\nenabled=1\ngpgkey=https://keyserver.tyk.io/tyk.io.rpm.signing.key.2020 https://packagecloud.io/tyk/tyk-dashboard/gpgkey\nsslverify=1\nsslcacert=/etc/pki/tls/certs/ca-bundle.crt\nmetadata_expire=300" > /etc/yum.repos.d/tyk_tyk-dashboard.repo

# Update our local cache
RUN yum -q makecache -y --disablerepo='*' --enablerepo='tyk_tyk-dashboard'

# Install Tyk Dashboard
RUN yum install -y tyk-dashboard 
RUN /opt/tyk-dashboard/install/setup.sh --listenport=3000 --redishost=127.0.0.1 --redisport=6379 --mongo=mongodb://127.0.0.1:27017/tyk_analytics --tyk_api_hostname=$HOSTNAME --tyk_node_hostname=http://localhost --tyk_node_port=8080 --portal_root=/portal --domain="127.0.0.1"
RUN systemctl enable tyk-dashboard

VOLUME ["/opt/tyk-dashboard"]

WORKDIR /opt/tyk-dashboard

ENTRYPOINT ["/opt/tyk-dashboard/tyk-analytics", "--conf=/opt/tyk-dashboard/tyk_analytics.conf"]